"""Migrate parseMatch

Revision ID: 174aab2284bc
Revises: 73815967fc44
Create Date: 2022-10-30 01:39:22.260199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '174aab2284bc'
down_revision = '73815967fc44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parseMatch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matchId', sa.String(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parseMatch_id'), 'parseMatch', ['id'], unique=True)
    op.create_index(op.f('ix_parseMatch_matchId'), 'parseMatch', ['matchId'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parseMatch_matchId'), table_name='parseMatch')
    op.drop_index(op.f('ix_parseMatch_id'), table_name='parseMatch')
    op.drop_table('parseMatch')
    # ### end Alembic commands ###
