"""Add match, participant table

Revision ID: 1e7a87b9e9fa
Revises: d965d373fd43
Create Date: 2022-11-18 02:00:08.010986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e7a87b9e9fa'
down_revision = 'd965d373fd43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
