"""Add match_id nullable

Revision ID: 2a6ce51b0446
Revises: e83eaa15582f
Create Date: 2022-11-22 08:51:37.083722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a6ce51b0446'
down_revision = 'e83eaa15582f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
