"""Migrate tables

Revision ID: 66c53038a900
Revises: 
Create Date: 2022-11-21 19:22:09.637154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66c53038a900'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_id'), 'game', ['id'], unique=True)
    op.create_table('match',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('queue_mode', sa.String(), nullable=True),
    sa.Column('game_duration', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('summoner',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('puuid', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('profile_icon_id', sa.String(), nullable=True),
    sa.Column('kda_avg', sa.Float(), nullable=True),
    sa.Column('kills_avg', sa.Float(), nullable=True),
    sa.Column('deaths_avg', sa.Float(), nullable=True),
    sa.Column('assists_avg', sa.Float(), nullable=True),
    sa.Column('prefer_position', sa.String(), nullable=True),
    sa.Column('prefer_position_rate', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('puuid')
    )
    op.create_table('train_game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.String(), nullable=True),
    sa.Column('is_parsed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_train_game_id'), 'train_game', ['id'], unique=True)
    op.create_index(op.f('ix_train_game_match_id'), 'train_game', ['match_id'], unique=True)
    op.create_table('champion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('summoner_id', sa.String(), nullable=True),
    sa.Column('champion_name', sa.String(), nullable=True),
    sa.Column('counts', sa.Integer(), nullable=True),
    sa.Column('kills', sa.Integer(), nullable=True),
    sa.Column('deaths', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['summoner_id'], ['summoner.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('code',
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('match_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.PrimaryKeyConstraint('value')
    )
    op.create_index(op.f('ix_code_value'), 'code', ['value'], unique=True)
    op.create_table('participant',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.String(), nullable=True),
    sa.Column('summoner_name', sa.String(), nullable=True),
    sa.Column('champion_name', sa.String(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('rank', sa.String(), nullable=True),
    sa.Column('tier', sa.String(), nullable=True),
    sa.Column('champion_level', sa.Integer(), nullable=True),
    sa.Column('cs', sa.Integer(), nullable=True),
    sa.Column('spell1', sa.String(), nullable=True),
    sa.Column('spell2', sa.String(), nullable=True),
    sa.Column('perk', sa.String(), nullable=True),
    sa.Column('perk_style', sa.String(), nullable=True),
    sa.Column('item0', sa.Integer(), nullable=True),
    sa.Column('item1', sa.Integer(), nullable=True),
    sa.Column('item2', sa.Integer(), nullable=True),
    sa.Column('item3', sa.Integer(), nullable=True),
    sa.Column('item4', sa.Integer(), nullable=True),
    sa.Column('item5', sa.Integer(), nullable=True),
    sa.Column('item6', sa.Integer(), nullable=True),
    sa.Column('gold_earned', sa.Integer(), nullable=True),
    sa.Column('kills', sa.Integer(), nullable=True),
    sa.Column('deaths', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('total_damage_dealt_to_champions', sa.Integer(), nullable=True),
    sa.Column('total_damage_taken', sa.Integer(), nullable=True),
    sa.Column('vision_wards_bought_in_game', sa.Integer(), nullable=True),
    sa.Column('win', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('rank',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('summoner_id', sa.String(), nullable=True),
    sa.Column('tier', sa.String(), nullable=True),
    sa.Column('rank', sa.String(), nullable=True),
    sa.Column('lp', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('is_flex', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['summoner_id'], ['summoner.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rank')
    op.drop_table('participant')
    op.drop_index(op.f('ix_code_value'), table_name='code')
    op.drop_table('code')
    op.drop_table('champion')
    op.drop_index(op.f('ix_train_game_match_id'), table_name='train_game')
    op.drop_index(op.f('ix_train_game_id'), table_name='train_game')
    op.drop_table('train_game')
    op.drop_table('summoner')
    op.drop_table('match')
    op.drop_index(op.f('ix_game_id'), table_name='game')
    op.drop_table('game')
    # ### end Alembic commands ###
