"""Add vision_wards_bought_in_game column in participant table

Revision ID: 67d46fb30b71
Revises: 72bf0b74aea1
Create Date: 2022-11-18 23:57:25.438080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67d46fb30b71'
down_revision = '72bf0b74aea1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant', sa.Column('vision_wards_bought_in_game', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participant', 'vision_wards_bought_in_game')
    # ### end Alembic commands ###
