"""Add cs column in participant table

Revision ID: 72bf0b74aea1
Revises: d55902a5dc4c
Create Date: 2022-11-18 23:50:26.677051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72bf0b74aea1'
down_revision = 'd55902a5dc4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'match', ['id'])
    op.add_column('participant', sa.Column('cs', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'participant', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'participant', type_='unique')
    op.drop_column('participant', 'cs')
    op.drop_constraint(None, 'match', type_='unique')
    # ### end Alembic commands ###
