"""Alter value to string

Revision ID: 73815967fc44
Revises: 0d57f9829f69
Create Date: 2022-09-27 01:34:38.068800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73815967fc44'
down_revision = '0d57f9829f69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('code', 'value',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('code', 'value',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
