"""Create summoner table

Revision ID: 760197cc8197
Revises: c73ef71fe2f2
Create Date: 2022-11-10 15:18:41.549596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '760197cc8197'
down_revision = 'c73ef71fe2f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('summoner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('summoner_id', sa.String(), nullable=True),
    sa.Column('puuid', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('profile_icon_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('puuid'),
    sa.UniqueConstraint('summoner_id')
    )
    op.create_index(op.f('ix_summoner_id'), 'summoner', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_summoner_id'), table_name='summoner')
    op.drop_table('summoner')
    # ### end Alembic commands ###
