"""Fix column from total_damage_take to total_damage_taken in participant table

Revision ID: 7ad815f9235f
Revises: 9f13a8dd1ab7
Create Date: 2022-11-19 03:28:02.311698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ad815f9235f'
down_revision = '9f13a8dd1ab7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant', sa.Column('total_damage_taken', sa.Integer(), nullable=True))
    op.drop_column('participant', 'total_damage_take')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant', sa.Column('total_damage_take', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('participant', 'total_damage_taken')
    # ### end Alembic commands ###
