"""Add team_id column to participant table

Revision ID: 7f8f1a4383c6
Revises: 7ad815f9235f
Create Date: 2022-11-19 23:55:14.239532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f8f1a4383c6'
down_revision = '7ad815f9235f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant', sa.Column('team_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participant', 'team_id')
    # ### end Alembic commands ###
