"""Add tier column in participant table

Revision ID: 9f13a8dd1ab7
Revises: 67d46fb30b71
Create Date: 2022-11-19 03:07:16.790136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f13a8dd1ab7'
down_revision = '67d46fb30b71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant', sa.Column('tier', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participant', 'tier')
    # ### end Alembic commands ###
