"""Fix id to autoincrement

Revision ID: be2e8515a4d5
Revises: d840298a716c
Create Date: 2022-11-14 03:10:51.232200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be2e8515a4d5'
down_revision = 'd840298a716c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
