"""Change item index start from 1 to 0

Revision ID: c51c03fbfd52
Revises: 7f8f1a4383c6
Create Date: 2022-11-20 00:16:33.944319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c51c03fbfd52'
down_revision = '7f8f1a4383c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant', sa.Column('item0', sa.Integer(), nullable=True))
    op.drop_column('participant', 'item7')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant', sa.Column('item7', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('participant', 'item0')
    # ### end Alembic commands ###
