"""Change train_game's attribute from matchId to match_id

Revision ID: c73ef71fe2f2
Revises: f8a17334f1c3
Create Date: 2022-10-30 16:38:26.623352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c73ef71fe2f2'
down_revision = 'f8a17334f1c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('train_game', sa.Column('match_id', sa.String(), nullable=True))
    op.drop_index('ix_train_game_matchId', table_name='train_game')
    op.create_index(op.f('ix_train_game_match_id'), 'train_game', ['match_id'], unique=True)
    op.drop_column('train_game', 'matchId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('train_game', sa.Column('matchId', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_train_game_match_id'), table_name='train_game')
    op.create_index('ix_train_game_matchId', 'train_game', ['matchId'], unique=False)
    op.drop_column('train_game', 'match_id')
    # ### end Alembic commands ###
