"""Add match, participant table

Revision ID: d55902a5dc4c
Revises: eba14e473ad1
Create Date: 2022-11-18 18:13:14.673499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd55902a5dc4c'
down_revision = 'eba14e473ad1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('queue_mode', sa.String(), nullable=True),
    sa.Column('game_duration', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('participant',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.String(), nullable=True),
    sa.Column('summoner_name', sa.String(), nullable=True),
    sa.Column('champion_name', sa.String(), nullable=True),
    sa.Column('rank', sa.String(), nullable=True),
    sa.Column('champion_level', sa.Integer(), nullable=True),
    sa.Column('spell1', sa.String(), nullable=True),
    sa.Column('spell2', sa.String(), nullable=True),
    sa.Column('perk', sa.String(), nullable=True),
    sa.Column('perk_style', sa.String(), nullable=True),
    sa.Column('item1', sa.Integer(), nullable=True),
    sa.Column('item2', sa.Integer(), nullable=True),
    sa.Column('item3', sa.Integer(), nullable=True),
    sa.Column('item4', sa.Integer(), nullable=True),
    sa.Column('item5', sa.Integer(), nullable=True),
    sa.Column('item6', sa.Integer(), nullable=True),
    sa.Column('item7', sa.Integer(), nullable=True),
    sa.Column('gold_earned', sa.Integer(), nullable=True),
    sa.Column('kills', sa.Integer(), nullable=True),
    sa.Column('deaths', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('total_damage_dealt_to_champions', sa.Integer(), nullable=True),
    sa.Column('total_damage_take', sa.Integer(), nullable=True),
    sa.Column('win', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participant')
    op.drop_table('match')
    # ### end Alembic commands ###
