"""Create summoner, champion, rank table relationship

Revision ID: d840298a716c
Revises: 76715fc93d62
Create Date: 2022-11-12 22:15:19.333446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd840298a716c'
down_revision = '76715fc93d62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('champion', sa.Column('summoner_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'champion', 'summoner', ['summoner_id'], ['id'])
    op.add_column('rank', sa.Column('summoner_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'rank', 'summoner', ['summoner_id'], ['id'])
    op.alter_column('summoner', 'puuid',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('summoner', 'puuid',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'rank', type_='foreignkey')
    op.drop_column('rank', 'summoner_id')
    op.drop_constraint(None, 'champion', type_='foreignkey')
    op.drop_column('champion', 'summoner_id')
    # ### end Alembic commands ###
