"""Add order column to champion

Revision ID: d965d373fd43
Revises: be2e8515a4d5
Create Date: 2022-11-14 21:55:40.088151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd965d373fd43'
down_revision = 'be2e8515a4d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('champion', sa.Column('order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('champion', 'order')
    # ### end Alembic commands ###
