"""Create summoner, champion, rank table

Revision ID: dbdf5c800e66
Revises: c63283eca097
Create Date: 2022-11-12 21:58:38.868338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbdf5c800e66'
down_revision = 'c63283eca097'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('champion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('summoner_id', sa.String(), nullable=True),
    sa.Column('champion_name', sa.String(), nullable=True),
    sa.Column('counts', sa.Integer(), nullable=True),
    sa.Column('kills', sa.Integer(), nullable=True),
    sa.Column('deaths', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['summoner_id'], ['summoner.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('summoner_id', sa.String(), nullable=True),
    sa.Column('tier', sa.String(), nullable=True),
    sa.Column('rank', sa.String(), nullable=True),
    sa.Column('lp', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('is_flex', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['summoner_id'], ['summoner.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('summoner', sa.Column('kda_avg', sa.Float(), nullable=True))
    op.add_column('summoner', sa.Column('kills_avg', sa.Float(), nullable=True))
    op.add_column('summoner', sa.Column('deaths_avg', sa.Float(), nullable=True))
    op.add_column('summoner', sa.Column('assists_avg', sa.Float(), nullable=True))
    op.add_column('summoner', sa.Column('prefer_position', sa.String(), nullable=True))
    op.add_column('summoner', sa.Column('prefer_position_rate', sa.Float(), nullable=True))
    op.alter_column('summoner', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('summoner', 'puuid',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_summoner_id', table_name='summoner')
    op.drop_constraint('summoner_summoner_id_key', 'summoner', type_='unique')
    op.create_unique_constraint(None, 'summoner', ['id'])
    op.drop_column('summoner', 'summoner_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('summoner', sa.Column('summoner_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'summoner', type_='unique')
    op.create_unique_constraint('summoner_summoner_id_key', 'summoner', ['summoner_id'])
    op.create_index('ix_summoner_id', 'summoner', ['id'], unique=False)
    op.alter_column('summoner', 'puuid',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('summoner', 'id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('summoner', 'prefer_position_rate')
    op.drop_column('summoner', 'prefer_position')
    op.drop_column('summoner', 'assists_avg')
    op.drop_column('summoner', 'deaths_avg')
    op.drop_column('summoner', 'kills_avg')
    op.drop_column('summoner', 'kda_avg')
    op.drop_table('rank')
    op.drop_table('champion')
    # ### end Alembic commands ###
