"""Add match_id column to CodeCreate class

Revision ID: e83eaa15582f
Revises: 66c53038a900
Create Date: 2022-11-22 08:49:08.973022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e83eaa15582f'
down_revision = '66c53038a900'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'match', ['id'])
    op.create_unique_constraint(None, 'participant', ['id'])
    op.create_unique_constraint(None, 'summoner', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'summoner', type_='unique')
    op.drop_constraint(None, 'participant', type_='unique')
    op.drop_constraint(None, 'match', type_='unique')
    # ### end Alembic commands ###
