"""Add match, participant table

Revision ID: eba14e473ad1
Revises: 1e7a87b9e9fa
Create Date: 2022-11-18 16:41:29.594934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eba14e473ad1'
down_revision = '1e7a87b9e9fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
