"""Migrate trainMatch

Revision ID: f8a17334f1c3
Revises: 174aab2284bc
Create Date: 2022-10-30 02:52:31.509297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8a17334f1c3'
down_revision = '174aab2284bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('train_game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matchId', sa.String(), nullable=True),
    sa.Column('is_parsed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_train_game_id'), 'train_game', ['id'], unique=True)
    op.create_index(op.f('ix_train_game_matchId'), 'train_game', ['matchId'], unique=True)
    op.drop_index('ix_parseMatch_id', table_name='parseMatch')
    op.drop_index('ix_parseMatch_matchId', table_name='parseMatch')
    op.drop_table('parseMatch')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parseMatch',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"parseMatch_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('matchId', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='parseMatch_pkey')
    )
    op.create_index('ix_parseMatch_matchId', 'parseMatch', ['matchId'], unique=False)
    op.create_index('ix_parseMatch_id', 'parseMatch', ['id'], unique=False)
    op.drop_index(op.f('ix_train_game_matchId'), table_name='train_game')
    op.drop_index(op.f('ix_train_game_id'), table_name='train_game')
    op.drop_table('train_game')
    # ### end Alembic commands ###
